### ISSUE TITLE
TicketRegistryCleaner出错

### ISSUE THREAD

**Issue by Odinysus** [izerui/cas-server-integration-redis#2]
java 8
tomcat 8.5
redis 3.2
cas 4.3.2

在我运行一段时间之后,如果我重启就会出现一下出错
```
2017-08-10 18:00:36,269 ERROR [org.quartz.core.ErrorLogger] - <Job (DEFAULT.TicketRegistryCleaner7ac20fc8-66dd-4e1b-82f4-074fc7fe8c3c threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.AbstractMethodError: org.jasig.cas.ticket.registry.AbstractTicketRegistry.deleteSingleTicket(Ljava/lang/String;)Z]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.AbstractMethodError: org.jasig.cas.ticket.registry.AbstractTicketRegistry.deleteSingleTicket(Ljava/lang/String;)Z
	at org.jasig.cas.ticket.registry.AbstractTicketRegistry.deleteTicket(AbstractTicketRegistry.java:98)
	at org.jasig.cas.ticket.registry.TicketRegistryCleaner$1.apply(TicketRegistryCleaner.java:129)
	at org.jasig.cas.ticket.registry.TicketRegistryCleaner$1.apply(TicketRegistryCleaner.java:1)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.jasig.cas.ticket.registry.TicketRegistryCleaner.execute(TicketRegistryCleaner.java:139)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
```

下面是deployerConfigContext.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:c="http://www.springframework.org/schema/c"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:ldaptive="http://www.ldaptive.org/schema/spring-ext"
       xmlns:sec="http://www.springframework.org/schema/security"

       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx.xsd
       http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
       http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security.xsd
       http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd
       http://www.ldaptive.org/schema/spring-ext http://www.ldaptive.org/schema/spring-ext.xsd
       ">


    <util:map id="authenticationHandlersResolvers">
        <entry key-ref="proxyAuthenticationHandler" value-ref="proxyPrincipalResolver"/>
        <!--<entry key-ref="primaryAuthenticationHandler" value-ref="primaryPrincipalResolver" />-->
        <entry key-ref="ldapAuthenticationHandler" value="#{null}" />
    </util:map>

    <bean id="ldapAuthenticationHandler"
          class="org.jasig.cas.authentication.LdapAuthenticationHandler"
          c:authenticator-ref="authenticator">
        <property name="principalAttributeList">
            <list>
                <value>uid</value>
            </list>
        </property>
    </bean>

    <util:list id="authenticationMetadataPopulators">
        <ref bean="successfulHandlerMetaDataPopulator"/>
        <ref bean="rememberMeAuthenticationMetaDataPopulator"/>
    </util:list>

    <bean id="attributeRepository" class="org.jasig.services.persondir.support.NamedStubPersonAttributeDao" />

   <alias name="personDirectoryPrincipalResolver" alias="primaryPrincipalResolver"/>

    <alias name="serviceThemeResolver" alias="themeResolver"/>

    <alias name="jsonServiceRegistryDao" alias="serviceRegistryDao"/>

    <!--<alias name="defaultTicketRegistry" alias="ticketRegistry"/>-->

    <alias name="ticketGrantingTicketExpirationPolicy" alias="grantingTicketExpirationPolicy"/>
    <alias name="multiTimeUseOrTimeoutExpirationPolicy" alias="serviceTicketExpirationPolicy"/>

    <alias name="anyAuthenticationPolicy" alias="authenticationPolicy"/>
    <alias name="acceptAnyAuthenticationPolicyFactory" alias="authenticationPolicyFactory"/>

    <bean id="auditTrailManager"
          class="org.jasig.inspektr.audit.support.Slf4jLoggingAuditTrailManager"
          p:useSingleLine="${cas.audit.singleline:false}"/>

    <alias name="neverThrottle" alias="authenticationThrottle"/>

    <util:list id="monitorsList">
        <ref bean="memoryMonitor"/>
        <ref bean="sessionMonitor"/>
    </util:list>

    <alias name="defaultPrincipalFactory" alias="principalFactory"/>
    <alias name="defaultAuthenticationTransactionManager" alias="authenticationTransactionManager"/>
    <alias name="defaultPrincipalElectionStrategy" alias="principalElectionStrategy"/>
    <alias name="tgcCipherExecutor" alias="defaultCookieCipherExecutor"/>

    <ldaptive:bind-search-authenticator id="authenticator"
                                        ldapUrl="${ldap.url}"
                                        baseDn="${ldap.baseDn}"
                                        userFilter="${ldap.authn.searchFilter}"
                                        bindDn="${ldap.managerDn}"
                                        bindCredential="${ldap.managerPassword}"
                                        connectTimeout="${ldap.connectTimeout}"
                                        useStartTLS="${ldap.useStartTLS}"
                                        blockWaitTime="${ldap.pool.blockWaitTime}"
                                        maxPoolSize="${ldap.pool.maxSize}"
                                        allowMultipleDns="${ldap.allowMultipleDns:false}"
                                        usePasswordPolicy="${ldap.usePpolicy:false}"
                                        minPoolSize="${ldap.pool.minSize}"
                                        validateOnCheckOut="${ldap.pool.validateOnCheckout}"
                                        validatePeriodically="${ldap.pool.validatePeriodically}"
                                        validatePeriod="${ldap.pool.validatePeriod}"
                                        idleTime="${ldap.pool.idleTime}"
                                        prunePeriod="${ldap.pool.prunePeriod}"
                                        failFastInitialize="true"
                                        subtreeSearch="${ldap.subtree.search:true}"
                                        useSSL="${ldap.use.ssl:false}"
    />


    <!-- 票据保存方式及有效期设置 -->
    <alias name="redisTicketRegistry" alias="ticketRegistry" />
    <bean id="redisTicketRegistry" class="ren.boot.cas.ticket.registry.RedisTicketRegistry"
          p:client-ref="ticketRedisTemplate"
          p:tgtTimeout="3600000"
          p:stTimeout="20000"
    />
    <!-- redis连接池 -->
    <bean id="jedisConnFactory"
          class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"
          p:hostName="localhost"
          p:port="6379"
          p:poolConfig-ref="poolConfig"
    />
    <bean id="poolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxIdle" value="300" />
        <property name="maxTotal" value="60000" />
        <property name="maxWaitMillis" value="2000" />
        <property name="testOnBorrow" value="true" />
        <property name="testOnReturn" value="true" />
    </bean>
    <bean id="ticketRedisTemplate" class="ren.boot.cas.ticket.registry.TicketRedisTemplate"
          p:connectionFactory-ref="jedisConnFactory">
    </bean>


</beans>

```

**Comment by izerui** [comment]
貌似没看到官方有发布4.3.2这个版本，再者：票据默认都有消亡时间的，理论上不需要自动任务做清理动作，这个TicketRegistryCleaner 在4.2.x版本中是不存在的。如果是5.x版本可以直接使用官方中已经集成redis ticket

**Comment by Odinysus** [comment]
已改用5.x版本
