### ISSUE TITLE
使用该模块后抛出异常'principal' cannot be null.

### ISSUE THREAD

**Issue by szxdlut** [izerui/cas-server-integration-redis#5]
cas4.2.7使用官方的memcached存储ticket没有问题，替换为该redis模块后，在验证ST阶段，抛出异常
 DEBUG org.springframework.data.redis.core.RedisConnectionUtils - Opening RedisConnection
2018-09-12 09:48:05 2018-09-12 09:48:05,554 [resin-port-10.61.20.207:10027-7583] DEBUG org.springframework.data.redis.core.RedisConnectionUtils - Closing Redis Connection
2018-09-12 09:48:05 2018-09-12 09:48:05,554 [resin-port-10.61.20.207:10027-7583] DEBUG ren.boot.cas.ticket.registry.RedisTicketRegistry - Removing ticket [org.jasig.cas.ticket.registry.ServiceTicketDelegator@87964ba0] from the registry.
2018-09-12 09:48:05 2018-09-12 09:48:05,554 [resin-port-10.61.20.207:10027-7583] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolving exception from handler [protected org.springframework.web.servlet.ModelAndView org.jasig.cas.web.v3.V3ServiceValidateController.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]: java.lang.IllegalArgumentException: 'principal' cannot be null.
                    Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.validation.Assertion org.jasig.cas.CentralAuthenticationService.validateServiceTicket(java.lang.String,org.jasig.cas.authentication.principal.Service))
2018-09-12 09:48:05 2018-09-12 09:48:05,557 [resin-port-10.61.20.207:10027-7583] DEBUG org.springframework.web.servlet.mvc.annotation.ResponseStatusExceptionResolver - Resolving exception from handler [protected org.springframework.web.servlet.ModelAndView org.jasig.cas.web.v3.V3ServiceValidateController.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]: java.lang.IllegalArgumentException: 'principal' cannot be null.
                    Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.validation.Assertion org.jasig.cas.CentralAuthenticationService.validateServiceTicket(java.lang.String,org.jasig.cas.authentication.principal.Service))
2018-09-12 09:48:05 2018-09-12 09:48:05,557 [resin-port-10.61.20.207:10027-7583] DEBUG org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolving exception from handler [protected org.springframework.web.servlet.ModelAndView org.jasig.cas.web.v3.V3ServiceValidateController.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]: java.lang.IllegalArgumentException: 'principal' cannot be null.
                    Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.validation.Assertion org.jasig.cas.CentralAuthenticationService.validateServiceTicket(java.lang.String,org.jasig.cas.authentication.principal.Service))
2018-09-12 09:48:05 2018-09-12 09:48:05,557 [resin-port-10.61.20.207:10027-7583] DEBUG org.jasig.cas.web.FlowExecutionExceptionResolver - Ignoring the received exception due to a type mismatch
                    java.lang.IllegalArgumentException: 'principal' cannot be null.
                    Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.validation.Assertion org.jasig.cas.CentralAuthenticationService.validateServiceTicket(java.lang.String,org.jasig.cas.authentication.principal.Service))
                        at org.jasig.inspektr.audit.AuditActionContext.assertNotNull(AuditActionContext.java:80)
                        at org.jasig.inspektr.audit.AuditActionContext.<init>(AuditActionContext.java:62)
                        at org.jasig.inspektr.audit.AuditTrailManagementAspect.executeAuditCode(AuditTrailManagementAspect.java:153)
                        at org.jasig.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:141)
                        at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:497)
                        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:620)
                        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:609)
                        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
                        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
                        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
                        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                        at com.ryantenney.metrics.spring.MeteredMethodInterceptor.invoke(MeteredMethodInterceptor.java:45)
                        at com.ryantenney.metrics.spring.MeteredMethodInterceptor.invoke(MeteredMethodInterceptor.java:32)
                        at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
                        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                        at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:48)
                        at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:34)
                        at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
                        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                        at com.ryantenney.metrics.spring.CountedMethodInterceptor.invoke(CountedMethodInterceptor.java:46)
                        at com.ryantenney.metrics.spring.CountedMethodInterceptor.invoke(CountedMethodInterceptor.java:32)
                        at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
                        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
                        at com.sun.proxy.$Proxy101.validateServiceTicket(Unknown Source)
                        at org.jasig.cas.web.AbstractServiceValidateController.handleRequestInternal(AbstractServiceValidateController.java:230)
                        at org.jasig.cas.web.v3.V3ServiceValidateController.handle(V3ServiceValidateController.java:35)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:497)
                        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
                        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
                        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
                        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832)
                        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743)
                        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
                        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
                        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
                        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
                        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:120)
                        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:97)
                        at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
                        at org.apereo.cas.security.ResponseHeadersEnforcementFilter.doFilter(ResponseHeadersEnforcementFilter.java:238)
                        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
                        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
                        at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
                        at org.apereo.cas.security.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:261)
                        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
                        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
                        at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
                        at org.jasig.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:62)
                        at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
                        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
                        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
                        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
                        at com.caucho.server.dispatch.FilterFilterChain.doFilter(FilterFilterChain.java:89)
                        at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:156)
                        at com.caucho.server.webapp.AccessLogFilterChain.doFilter(AccessLogFilterChain.java:95)
                        at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:289)
                        at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:838)
                        at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:1342)
                        at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:1298)
                        at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:1282)
                        at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:1190)
                        at com.caucho.network.listen.TcpSocketLink.handleAcceptTaskImpl(TcpSocketLink.java:989)
                        at com.caucho.network.listen.ConnectionTask.runThread(ConnectionTask.java:117)
                        at com.caucho.network.listen.ConnectionTask.run(ConnectionTask.java:93)
                        at com.caucho.network.listen.SocketLinkThreadLauncher.handleTasks(SocketLinkThreadLauncher.java:169)
                        at com.caucho.network.listen.TcpSocketAcceptThread.run(TcpSocketAcceptThread.java:61)
                        at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
                        at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)

**Comment by izerui** [comment]
参考下： https://blog.csdn.net/pucao_cug/article/details/70187542
